### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by rickyoleary** [thundermiracle/filter-data#109]
Hi, I was after something like this for a system we're designing. Do you plan to add date filters? For example, if I use greater than and pass a date, I'd expect results where the date is greater than specified.

**Comment by rickyoleary** [comment]
The same applies for booleans. I can't compare where a boolean is true or false.

**Comment by thundermiracle** [comment]
> if I use greater than and pass a date

The feature request is 
- Passing a date in search condition, compare to data which are `date string`s.

Am I right?

**Comment by rickyoleary** [comment]
That is correct. As well as booleans. For example, your EQ operator on boolean flags causes an error. Like (LK) worked, however.

Also, with dates, it seemed in my tests yyyy-mm-dd format actually worked as it's the natural sort for strings. But if a date format is different, it'll fail.

**Comment by thundermiracle** [comment]
OK, I'll try to implement it anyway.

**Comment by thundermiracle** [comment]
You can filter date right now.
https://codesandbox.io/s/filter-data-react-iw534?file=/src/getData.js

**Comment by rickyoleary** [comment]
Works great, good work and thank you.
