### ISSUE TITLE
Support filtering on deep nested object

### ISSUE THREAD

**Issue by rachitpsolanki** [thundermiracle/filter-data#24]
Need support for filtering deep nested objects

EG. 
`
[
  {
 "id":1,
"user":{
"firstName":'Mike'}
  }
]
`

`{
    key: [['user','firstName']],
    value: 'dan',
    type: SearchType.LK,
  }`

**Comment by rachitpsolanki** [comment]
https://github.com/thundermiracle/filter-data/pull/25

**Comment by rachitpsolanki** [comment]
@thundermiracle Can you check the PR.

I am trying to solve the problem for filtering deep nested object

**Comment by thundermiracle** [comment]
Thanks! I'll review it ASAP.

**Comment by rachitpsolanki** [comment]
Thanks @thundermiracle, Looking forward for the PR to reviewed and merge

**Comment by thundermiracle** [comment]
Thanks for your contribution!
I merged your PR just right now. And after adding some tests for this new feature, I'll publish a new version.

**Comment by thundermiracle** [comment]
`0.2.0` is released just now. 

https://github.com/thundermiracle/filter-data/releases/tag/0.2.0

**Comment by rachitpsolanki** [comment]
Thanks @thundermiracle Much appreciated.
